<a href="https://colab.research.google.com/github/Kashish-mogha26/PyTorch/blob/master/1D_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
# Define w = 2 and b = -1 for y = wx + b
w=torch.tensor(2.0,requires_grad=True)
b=torch.tensor(-1.0,requires_grad=True)

In [0]:
# Function forward(x) for prediction
def forward(x):
  y=w*x+b
  return y

In [4]:
# Predict y = 2x - 1 at x = 1
x=torch.tensor([1.0])
yhat=forward(x)
print("The prediction:",yhat)

The prediction: tensor([1.], grad_fn=<AddBackward0>)


In [5]:
#prediction for multiple inputs:
x=torch.tensor([[1.0],[2.0]])
print('The shape of x is:',x.shape)


The shape of x is: torch.Size([2, 1])


In [6]:
yhat=forward(x)
print("The prediction:",yhat)

The prediction: tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [7]:
#LINEAR CLASS
from torch.nn import Linear
torch.manual_seed(1) #set random seed bcoz parameters are randomly initialized
model=Linear(in_features=1,out_features=1)
print("Parameters w and b: ", list(model.parameters()))
x=torch.tensor([1.0])
yhat=model(x)
print('The prediction:',yhat)


Parameters w and b:  [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
The prediction: tensor([0.0739], grad_fn=<AddBackward0>)


In [0]:
#CUSTOM MODULE
from torch import nn

In [0]:
#CUSTOMIZE LINEAR REGRESSION CLASS
class LR(nn.Module):
  #CONSTRUCTOR
  def __init__(self,input_size,output_size):
    super(LR,self).__init__()
    self.linear=nn.Linear(input_size,output_size)
  def forward(self,x):
    out=self.linear(x)
    return out

In [0]:
# Create the linear regression model. Print out the parameters.

model = LR(1, 1)
print("The parameters: ", list(model.parameters()))
print("Linear model: ", model.linear)

The parameters:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [0]:
x = torch.tensor([[1.0], [2.0]])
yhat = model(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward>)
